# Generated by Django 2.0.3 on 2018-03-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='_type',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='_type2',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='pizzas',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
