# Generated by Django 2.0.3 on 2018-03-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_auto_20180329_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(max_length=10)),
                ('items', models.CharField(max_length=15)),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lprice', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('pizzas', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Pizza')),
            ],
        ),
    ]
