# Generated by Django 2.0.3 on 2018-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180402_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subs',
            field=models.ManyToManyField(blank=True, to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='order',
            name='subs',
            field=models.ManyToManyField(blank=True, to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='sub',
            name='user',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
