# Generated by Django 2.0.3 on 2018-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180403_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMenu', models.BooleanField(default=True)),
                ('user', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=6.5, max_digits=4)),
            ],
        ),
    ]
