# Generated by Django 2.0.3 on 2018-04-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_pasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMenu', models.BooleanField(default=True)),
                ('user', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=35, max_digits=4)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMenu', models.BooleanField(default=True)),
                ('user', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=6.25, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='pasta',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='order',
            name='pasta',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='cart',
            name='salads',
            field=models.ManyToManyField(blank=True, to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ManyToManyField(blank=True, to='orders.Salad'),
        ),
    ]
