# Generated by Django 2.0.3 on 2018-03-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180329_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Item'),
        ),
    ]
