# Generated by Django 2.0.3 on 2018-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180403_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='platters',
            field=models.ManyToManyField(blank=True, to='orders.Dinner_Platter'),
        ),
        migrations.AddField(
            model_name='order',
            name='platters',
            field=models.ManyToManyField(blank=True, to='orders.Dinner_Platter'),
        ),
    ]
