# Generated by Django 2.0.3 on 2018-03-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
