# Generated by Django 2.0.3 on 2018-03-31 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
